language: node_js
node_js:
  - "8"
before_script:
  - cd test
  - rm -f client_secrets.json
  - echo "{\"kkbox_sdk\": {\"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\"}}" >> client_secrets.json
  - cd ..