language: node_js
env:
  - FORCE_COLOR=true
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
cache:
  directories:
    - node_modules
before_script:
  - |
    echo -e "{\"kkbox_sdk\": {\"client_id\": \"$CLIENT_ID\", \"client_secret\": \"$CLIENT_SECRET\"}}" > client_secrets.json
